/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BindingUiModule extends fr.inria.diverse.puzzle.language.ui.AbstractBindingUiModule {
	public BindingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
