/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractMutivarValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.diverse.puzzle.multivar.metamodel"));
		return result;
	}
}
