/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.ui.contentassist;

import fr.inria.diverse.puzzle.adl.ui.contentassist.AbstractLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
