<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flowchartpck" nsURI="http://flowchartmt/" nsPrefix="flowchartpck">
  <eClassifiers xsi:type="ecore:EClass" name="Flowchart">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="//Arc" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//Arc" eOpposite="//Arc/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//Arc" eOpposite="//Arc/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Hashtable" instanceClassName="java.util.Hashtable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc">
    <eAnnotations source="gmf.link">
      <details key="label" value="name"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="//Node" eOpposite="//Node/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="//Node" eOpposite="//Node/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subflow" eSuperTypes="//Flowchart //Node">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="org.eclipse.epsilon.eugenia.examples.flowchart.diagram.figures.SquareFigure"/>
    </eAnnotations>
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="org.eclipse.epsilon.eugenia.examples.flowchart.diagram.figures.DiamondFigure"/>
    </eAnnotations>
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalConstraint" eSuperTypes="//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="//Expression">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLit" eSuperTypes="//Literal">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLit" eSuperTypes="//Literal">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLit" eSuperTypes="//Literal">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="//Expression">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="//ArithmeticOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="mult" value="2"/>
    <eLiterals name="div" value="3" literal="div"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression" eSuperTypes="//Expression">
    <eOperations name="eval" eType="//Object">
      <eAnnotations source="aspect"/>
      <eParameters name="context" eType="//Hashtable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="//RelationalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperator">
    <eLiterals name="lessThan" literal="lessThan"/>
    <eLiterals name="greaterThan" value="1" literal="greaterThan"/>
    <eLiterals name="equals" value="2" literal="equals"/>
    <eLiterals name="notEqual" value="3" literal="notEqual"/>
    <eLiterals name="lessThanOrEqualTo" value="4" literal="lessThanOrEqualTo"/>
    <eLiterals name="greaterThanOrEqualTo" value="5" literal="greaterThanOrEqualTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarReference" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
