/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PuzzleRuntimeModule extends fr.inria.diverse.puzzle.adl.language.AbstractPuzzleRuntimeModule {

}
