/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PuzzleUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.inria.diverse.puzzle.adl.language.ui.internal.PuzzleActivator.getInstance().getInjector("fr.inria.diverse.puzzle.adl.language.Puzzle");
	}
	
}
