/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language.ui.contentassist

import fr.inria.diverse.puzzle.language.ui.contentassist.AbstractBindingProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BindingProposalProvider extends AbstractBindingProposalProvider {
}
