/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.puzzle.services.MutivarGrammarAccess;

public class MutivarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MutivarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.puzzle.parser.antlr.internal.InternalMutivarParser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.puzzle.parser.antlr.internal.InternalMutivarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LanguageProductLine";
	}
	
	public MutivarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MutivarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
