/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.validation;

import fr.inria.diverse.puzzle.adl.validation.AbstractLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LanguageValidator extends AbstractLanguageValidator {
}
