<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CommonBehaviorReq" nsURI="http://fr.inria.diverse.puzzle.uml/CommonBehaviorReq" nsPrefix="CommonBehaviorReq">
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="//RedefinableElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true" eSuperTypes="//Classifier">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueExpression">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="//Classifier">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
