<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CommonBehaviorProv" nsURI="http://fr.inria.diverse.puzzle.uml/CommonBehaviorProv" nsPrefix="CommonBehaviorProv">
  <eClassifiers xsi:type="ecore:EClass" name="BehavioredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBehavior" upperBound="-1" eType="//Behavior" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierBehavior" eType="//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReentrant">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="//BehavioredClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedBehavior" upperBound="-1" eType="//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="//BehavioralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueBehavior" eSuperTypes="//Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBehavior" eSuperTypes="//OpaqueBehavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioralFeature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1" eType="//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reception" eSuperTypes="//BehavioralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1" eType="//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEvent" abstract="true" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyReceiveEvent" eSuperTypes="//MessageEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalEvent" eSuperTypes="//MessageEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1" eType="//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallEvent" eSuperTypes="//MessageEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelative">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" lowerBound="1" eType="//TimeExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observation" upperBound="-1" eType="//Observation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeObservation" eSuperTypes="//Observation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstEvent">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationObservation" eSuperTypes="//Observation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstEvent">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Duration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observation" upperBound="-1" eType="//Observation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interval"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeInterval" eSuperTypes="//Interval">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeMax" lowerBound="1" eType="//TimeExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeMin" lowerBound="1" eType="//TimeExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationInterval" eSuperTypes="//Interval">
    <eStructuralFeatures xsi:type="ecore:EReference" name="durationMax" lowerBound="1" eType="//Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="durationMin" lowerBound="1" eType="//Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1" eType="//Interval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeConstraint" eSuperTypes="//IntervalConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstEvent">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeSpecification" lowerBound="1" eType="//TimeInterval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationConstraint" eSuperTypes="//IntervalConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstEvent">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="durationSpecification" lowerBound="1" eType="//DurationInterval"/>
  </eClassifiers>
</ecore:EPackage>
