var G = new jsnx.DiGraph();
G.addNodesFrom(["Trigger: [fsm, hfsm, tfsm]"], {group:0});
G.addNodesFrom(["Statement: [fsm, hfsm, tfsm]"], {group:1});
G.addNodesFrom(["Constraint: [fsm, hfsm, tfsm]"], {group:2});
G.addNodesFrom(["NamedElement: [fsm, hfsm, tfsm]"], {group:3});
G.addNodesFrom(["Transition: [fsm]","AbstractState: [fsm]"], {group:4});
G.addNodesFrom(["StateMachine: [fsm]"], {group:5});
G.addNodesFrom(["Program: [fsm, hfsm, tfsm]"], {group:6});
G.addNodesFrom(["State: [fsm, hfsm, tfsm]"], {group:7});
G.addNodesFrom(["PseudostateKind: [fsm, hfsm, tfsm]"], {group:8});
G.addNodesFrom(["Pseudostate: [fsm, hfsm, tfsm]"], {group:9});
G.addNodesFrom(["FinalState: [fsm, hfsm, tfsm]"], {group:10});
G.addNodesFrom(["Expression: [fsm, hfsm, tfsm]"], {group:11});
G.addNodesFrom(["RelationalConstraint: [fsm, hfsm, tfsm]"], {group:12});
G.addNodesFrom(["Conditional: [fsm, hfsm, tfsm]"], {group:13});
G.addNodesFrom(["Loop: [fsm, hfsm, tfsm]"], {group:14});
G.addNodesFrom(["VarDecl: [fsm, hfsm, tfsm]"], {group:15});
G.addNodesFrom(["Literal: [fsm, hfsm, tfsm]"], {group:16});
G.addNodesFrom(["IntegerLit: [fsm, hfsm, tfsm]"], {group:17});
G.addNodesFrom(["StringLit: [fsm, hfsm, tfsm]"], {group:18});
G.addNodesFrom(["BoolLit: [fsm, hfsm, tfsm]"], {group:19});
G.addNodesFrom(["ArithmeticOperator: [fsm, hfsm, tfsm]"], {group:20});
G.addNodesFrom(["ArithmeticExpression: [fsm, hfsm, tfsm]"], {group:21});
G.addNodesFrom(["RelationalOperator: [fsm, hfsm, tfsm]"], {group:22});
G.addNodesFrom(["RelationalExpression: [fsm, hfsm, tfsm]"], {group:23});
G.addNodesFrom(["VarReference: [fsm, hfsm, tfsm]"], {group:24});
G.addNodesFrom(["ConsoleOutput: [fsm, hfsm, tfsm]"], {group:25});
G.addNodesFrom(["Println: [fsm, hfsm, tfsm]"], {group:26});
G.addNodesFrom(["Print: [fsm, hfsm, tfsm]"], {group:27});
G.addNodesFrom(["Assignation: [fsm, hfsm, tfsm]"], {group:28});
G.addNodesFrom(["Wait: [fsm, hfsm, tfsm]"], {group:29});
G.addNodesFrom(["Transition: [hfsm]","AbstractState: [hfsm, tfsm]","Region: [hfsm, tfsm]"], {group:30});
G.addNodesFrom(["StateMachine: [hfsm, tfsm]"], {group:31});
G.addNodesFrom(["Transition: [tfsm]"], {group:32});

G.addEdgesFrom([["StateMachine: [fsm]","AbstractState: [fsm]"],["StateMachine: [fsm]","Transition: [fsm]"],["AbstractState: [fsm]","Transition: [fsm]"],["AbstractState: [fsm]","Transition: [fsm]"],["Transition: [fsm]","Trigger: [fsm, hfsm, tfsm]"],["Transition: [fsm]","AbstractState: [fsm]"],["Transition: [fsm]","AbstractState: [fsm]"],["Transition: [fsm]","Statement: [fsm, hfsm, tfsm]"],["Transition: [fsm]","Constraint: [fsm, hfsm, tfsm]"],["State: [fsm, hfsm, tfsm]","Program: [fsm, hfsm, tfsm]"],["State: [fsm, hfsm, tfsm]","Program: [fsm, hfsm, tfsm]"],["State: [fsm, hfsm, tfsm]","Program: [fsm, hfsm, tfsm]"],["Pseudostate: [fsm, hfsm, tfsm]","PseudostateKind: [fsm, hfsm, tfsm]"],["RelationalConstraint: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["Program: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Conditional: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["Conditional: [fsm, hfsm, tfsm]","Program: [fsm, hfsm, tfsm]"],["Loop: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["Loop: [fsm, hfsm, tfsm]","Program: [fsm, hfsm, tfsm]"],["VarDecl: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["ArithmeticExpression: [fsm, hfsm, tfsm]","ArithmeticOperator: [fsm, hfsm, tfsm]"],["ArithmeticExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["ArithmeticExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["RelationalExpression: [fsm, hfsm, tfsm]","RelationalOperator: [fsm, hfsm, tfsm]"],["RelationalExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["RelationalExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["Assignation: [fsm, hfsm, tfsm]","VarDecl: [fsm, hfsm, tfsm]"],["Assignation: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["StateMachine: [hfsm, tfsm]","Region: [hfsm, tfsm]"],["Region: [hfsm, tfsm]","AbstractState: [hfsm, tfsm]"],["Region: [hfsm, tfsm]","Transition: [hfsm]"],["AbstractState: [hfsm, tfsm]","Transition: [hfsm]"],["AbstractState: [hfsm, tfsm]","Transition: [hfsm]"],["AbstractState: [hfsm, tfsm]","Region: [hfsm, tfsm]"],["Transition: [hfsm]","Trigger: [fsm, hfsm, tfsm]"],["Transition: [hfsm]","AbstractState: [hfsm, tfsm]"],["Transition: [hfsm]","AbstractState: [hfsm, tfsm]"],["Transition: [hfsm]","Constraint: [fsm, hfsm, tfsm]"],["Transition: [hfsm]","Statement: [fsm, hfsm, tfsm]"],["Transition: [tfsm]","Trigger: [fsm, hfsm, tfsm]"],["Transition: [tfsm]","AbstractState: [hfsm, tfsm]"],["Transition: [tfsm]","AbstractState: [hfsm, tfsm]"],["Transition: [tfsm]","Constraint: [fsm, hfsm, tfsm]"],["StateMachine: [fsm]","NamedElement: [fsm, hfsm, tfsm]"],["AbstractState: [fsm]","NamedElement: [fsm, hfsm, tfsm]"],["Transition: [fsm]","NamedElement: [fsm, hfsm, tfsm]"],["State: [fsm, hfsm, tfsm]","AbstractState: [fsm]"],["Pseudostate: [fsm, hfsm, tfsm]","AbstractState: [fsm]"],["FinalState: [fsm, hfsm, tfsm]","State: [fsm, hfsm, tfsm]"],["RelationalConstraint: [fsm, hfsm, tfsm]","Constraint: [fsm, hfsm, tfsm]"],["Program: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Conditional: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Loop: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["VarDecl: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Literal: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["IntegerLit: [fsm, hfsm, tfsm]","Literal: [fsm, hfsm, tfsm]"],["StringLit: [fsm, hfsm, tfsm]","Literal: [fsm, hfsm, tfsm]"],["BoolLit: [fsm, hfsm, tfsm]","Literal: [fsm, hfsm, tfsm]"],["ArithmeticExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["RelationalExpression: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["VarReference: [fsm, hfsm, tfsm]","Expression: [fsm, hfsm, tfsm]"],["ConsoleOutput: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Println: [fsm, hfsm, tfsm]","ConsoleOutput: [fsm, hfsm, tfsm]"],["Print: [fsm, hfsm, tfsm]","ConsoleOutput: [fsm, hfsm, tfsm]"],["Assignation: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["Wait: [fsm, hfsm, tfsm]","Statement: [fsm, hfsm, tfsm]"],["StateMachine: [hfsm, tfsm]","NamedElement: [fsm, hfsm, tfsm]"],["Region: [hfsm, tfsm]","NamedElement: [fsm, hfsm, tfsm]"],["AbstractState: [hfsm, tfsm]","NamedElement: [fsm, hfsm, tfsm]"],["Transition: [hfsm]","NamedElement: [fsm, hfsm, tfsm]"],["Transition: [tfsm]","NamedElement: [fsm, hfsm, tfsm]"]]);
