<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kmLogo" nsURI="http://logomt/" nsPrefix="kmlogo">
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Context" instanceClassName="logo.Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true" eSuperTypes="//Instruction">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Back" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forward" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Left" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Right" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenDown" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenUp" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clear" eSuperTypes="//Primitive">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//Instruction">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExp" abstract="true" eSuperTypes="//Expression">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="//Expression">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerValue" eType="//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcCall" eSuperTypes="//Expression">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualArgs" upperBound="-1" eType="//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" eType="//ProcDeclaration" eOpposite="//ProcDeclaration/procCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcDeclaration" eSuperTypes="//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procCall" upperBound="-1" eType="//ProcCall" eOpposite="//ProcCall/declaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1" eType="//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="//Instruction">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1" eType="//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="//ControlStructure">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" lowerBound="1" eType="//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStructure" eSuperTypes="//Instruction">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="//ControlStructure">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="//ControlStructure">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCall" eSuperTypes="//Expression">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1" eType="//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Greater" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lower" eSuperTypes="//BinaryExp">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogoProgram">
    <eOperations name="eval">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="context" eType="//Context"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1" eType="//Instruction" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
