<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DeploymentsProv" nsURI="http://fr.inria.diverse.puzzle.uml/DeploymentsProv" nsPrefix="DeploymentsProv">
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="//DeployedArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedArtifact" upperBound="-1" eType="//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifestation" upperBound="-1" eType="//Manifestation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manifestation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="//DeploymentTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedNode" upperBound="-1" eType="//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEnvironment" eSuperTypes="//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationPath"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentTarget" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" upperBound="-1" eType="//Deployment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1" eType="//DeploymentTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedArtifact" upperBound="-1" eType="//DeployedArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" upperBound="-1" eType="//DeploymentSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployedArtifact" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentSpecification" eSuperTypes="//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentLocation">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionLocation">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" eType="//Deployment"/>
  </eClassifiers>
</ecore:EPackage>
