/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.puzzle.adl.language.ui.internal.PuzzleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PuzzleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PuzzleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PuzzleActivator.getInstance().getInjector(PuzzleActivator.FR_INRIA_DIVERSE_PUZZLE_ADL_LANGUAGE_PUZZLE);
	}
	
}
