<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ActionsProv" nsURI="http://fr.inria.diverse.puzzle.uml/ActionsProv" nsPrefix="ActionsProv">
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValue" upperBound="-1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputValue" upperBound="-1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin" eSuperTypes="//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin" eSuperTypes="//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValuePin" eSuperTypes="//InputPin"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationAction" abstract="true" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallAction" abstract="true" eSuperTypes="//InvocationAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynchronous">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" upperBound="-2" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallBehaviorAction" eSuperTypes="//CallAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallOperationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendSignalAction" eSuperTypes="//InvocationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BroadcastSignalAction" eSuperTypes="//InvocationAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SendObjectAction" eSuperTypes="//InvocationAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateObjectAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestroyObjectAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestIdentityAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadSelfAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecificationAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeatureAction" abstract="true" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadStructuralFeatureAction" eSuperTypes="//StructuralFeatureAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WriteStructuralFeatureAction" abstract="true" eSuperTypes="//StructuralFeatureAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddStructuralFeatureValueAction" eSuperTypes="//WriteStructuralFeatureAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveStructuralFeatureValueAction" eSuperTypes="//WriteStructuralFeatureAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearStructuralFeatureAction" eSuperTypes="//StructuralFeatureAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValue" lowerBound="1" upperBound="-1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endData" lowerBound="2" upperBound="-1" eType="//LinkEndData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkEndData" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="//InputPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" upperBound="-1" eType="//QualifierValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadLinkAction" eSuperTypes="//LinkAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WriteLinkAction" abstract="true" eSuperTypes="//LinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateLinkAction" eSuperTypes="//WriteLinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkEndCreationData" eSuperTypes="//LinkEndData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReplaceAll">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestroyLinkAction" eSuperTypes="//WriteLinkAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkEndDestructionData" eSuperTypes="//LinkEndData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDestroyDuplicates">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destroyAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnInformation" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replyValue" upperBound="-1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnmarshallAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" upperBound="-1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptEventAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnmarshall">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" upperBound="-1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptCallAction" eSuperTypes="//AcceptEventAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnInformation" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadExtendAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReclassifyObjectAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReplaceAll">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadlsClassifiedObjectAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartClassifierBehaviorAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartObjectBehaviorAction" eSuperTypes="//CallAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifierValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//InputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadLinkObjectEndAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadLinkObjectEndQualifierAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateLinkObjectAction" eSuperTypes="//CreateLinkAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReduceAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAction" abstract="true" eSuperTypes="//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadVariableAction" eSuperTypes="//VariableAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1" eType="//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WriteVariableAction" eSuperTypes="//VariableAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddVariableValueAction" eSuperTypes="//WriteVariableAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveVariableValueAction" eSuperTypes="//WriteVariableAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeAt" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearVariableAction" eSuperTypes="//VariableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RaiseExceptionAction" eSuperTypes="//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" lowerBound="1" eType="//InputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionInputPin" eSuperTypes="//InputPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromAction" lowerBound="1" eType="//Action" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
