<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompositeStructuresReq" nsURI="http://fr.inria.diverse.puzzle.uml.classes.metamodel/CompositeStructuresReq" nsPrefix="CompositeStructuresReq">
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="//Feature">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="2" upperBound="-1" eType="//ConnectorEnd" containment="true">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="//RedefinableElement">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuringClassifier" upperBound="-1" eType="//Classifier">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="//Namespace">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1" eType="//Feature">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableElement" abstract="true" eSuperTypes="//TypedElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="//StructuralFeature //ConnectableElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorEnd">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="//ConnectableElement">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partWithPort" eType="//Property">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="//ConnectableElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioredClassifier">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
