<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompositeStructuresProv" nsURI="http://fr.inria.diverse.puzzle.uml/CompositeStructuresProv" nsPrefix="CompositeStructuresProv">
  <eClassifiers xsi:type="ecore:EClass" name="StructuredClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBehavior">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isService">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConjugated">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedPort" upperBound="-1" eType="//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulatedClassifier" abstract="true" eSuperTypes="//StructuredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPort" upperBound="-1" eType="//Port" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collaboration" eSuperTypes="//StructuredClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationUse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationAction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onPort" eType="//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable"/>
</ecore:EPackage>
