/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.validation;

import fr.inria.diverse.puzzle.validation.AbstractMutivarValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MutivarValidator extends AbstractMutivarValidator {
}
