<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Primitive" nsURI="Primitive" nsPrefix="Primitive">
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Forward" eSuperTypes="//Primitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Right" eSuperTypes="//Primitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenUp" eSuperTypes="//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCall" eSuperTypes="//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1" eType="//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
