/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PuzzleStandaloneSetup extends PuzzleStandaloneSetupGenerated{

	public static void doSetup() {
		new PuzzleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

