/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.puzzle.ui.internal.MutivarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MutivarExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MutivarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MutivarActivator.getInstance().getInjector(MutivarActivator.FR_INRIA_DIVERSE_PUZZLE_MUTIVAR);
	}
	
}
