<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="triggersReq" nsURI="http://triggersReq" nsPrefix="triggersReq">
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eAnnotations source="Required"/>
    <eOperations name="evalTrigger">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="event">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
