<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ControlStructuresReq" nsURI="http://fr.inria.diverse.examples.logo.ControlStructuresReq" nsPrefix="ControlStructuresReq">
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true">
    <eAnnotations source="Required"/>
    <eOperations name="evalInstruction">
      <eAnnotations source="Required"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="context">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//Instruction">
    <eAnnotations source="Required"/>
    <eOperations name="eval">
      <eAnnotations source="Required"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="context">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
