/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.puzzle.adl.language.services.PuzzleGrammarAccess;

public class PuzzleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PuzzleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.puzzle.adl.language.parser.antlr.internal.InternalPuzzleParser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.puzzle.adl.language.parser.antlr.internal.InternalPuzzleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LanguageBinding";
	}
	
	public PuzzleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PuzzleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
