/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.inria.diverse.puzzle.adl.ui.internal.LanguageActivator.getInstance().getInjector("fr.inria.diverse.puzzle.adl.Language");
	}
	
}
