<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="VariablesReq" nsURI="http://fr.inria.diverse.examples.logo.variablesReq" nsPrefix="VariablesReq">
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//Instruction">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
