/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.ui.contentassist;

import fr.inria.diverse.puzzle.ui.contentassist.AbstractMutivarProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MutivarProposalProvider extends AbstractMutivarProposalProvider {
}
