/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.puzzle.language.services.BindingGrammarAccess;

public class BindingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BindingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.puzzle.language.parser.antlr.internal.InternalBindingParser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.puzzle.language.parser.antlr.internal.InternalBindingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LanguageBinding";
	}
	
	public BindingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BindingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
