/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BindingUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.inria.diverse.puzzle.language.ui.internal.BindingActivator.getInstance().getInjector("fr.inria.diverse.puzzle.language.Binding");
	}
	
}
