/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PuzzleUiModule extends fr.inria.diverse.puzzle.adl.language.ui.AbstractPuzzleUiModule {
	public PuzzleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
