<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BinaryExpressionsReq" nsURI="http://fr.inria.diverse.examples.logo.BinaryExpressionsReq" nsPrefix="BinaryExpressionsReq">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eAnnotations source="Required"/>
    <eOperations name="eval">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="context">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
