/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MutivarUiModule extends fr.inria.diverse.puzzle.ui.AbstractMutivarUiModule {
	public MutivarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
