/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MutivarUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.inria.diverse.puzzle.ui.internal.MutivarActivator.getInstance().getInjector("fr.inria.diverse.puzzle.Mutivar");
	}
	
}
