/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.puzzle.language.ui.internal.BindingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BindingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BindingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BindingActivator.getInstance().getInjector(BindingActivator.FR_INRIA_DIVERSE_PUZZLE_LANGUAGE_BINDING);
	}
	
}
