<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LogoProgram" nsURI="LogoProgram" nsPrefix="LogoProgram">
  <eClassifiers xsi:type="ecore:EClass" name="LogoProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1" eType="//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Back">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Left">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angle" eType="//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PenDown"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clear"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
