/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BindingRuntimeModule extends fr.inria.diverse.puzzle.language.AbstractBindingRuntimeModule {

}
