/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LanguageStandaloneSetup extends LanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new LanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

