/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.adl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends fr.inria.diverse.puzzle.adl.AbstractLanguageRuntimeModule {

}
