<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ComponentsReq" nsURI="http://fr.inria.diverse.puzzle.uml/ComponentsReq" nsPrefix="ComponentsReq">
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientDependency" upperBound="-1" eType="//Dependency">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Realization" eSuperTypes="//Abstraction">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstraction" eSuperTypes="//Dependency">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eAnnotations source="Required"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" lowerBound="1" upperBound="-1" eType="//NamedElement">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1" upperBound="-1" eType="//NamedElement">
      <eAnnotations source="Required"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="//Namespace">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="//NamedElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
