<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StateMachinesProv" nsURI="http://fr.inria.diverse.puzzle.uml/StateMachinesProv" nsPrefix="StateMachinesProv">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1" upperBound="-1" eType="//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoint" upperBound="-1" eType="//Pseudostate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachineState" upperBound="-1" eType="//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedStateMachine" upperBound="-1" eType="//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1" eType="//Vertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1" eType="//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedRegion" eType="//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="//Region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedTransition" eType="//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" eSuperTypes="//Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPointReference" eSuperTypes="//Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="//Pseudostate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="//Pseudostate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrthogonal">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSimple">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSubmachineState">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1" eType="//ConnectionPointReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPoint" upperBound="-1" eType="//Pseudostate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submachine" eType="//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" upperBound="-1" eType="//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedState" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolStateMachine" eSuperTypes="//StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conformance" upperBound="-1" eType="//ProtocolConformance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolConformance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificMachine" lowerBound="1" eType="//ProtocolStateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalMachine" lowerBound="1" eType="//ProtocolStateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolTransition" eSuperTypes="//Transition"/>
</ecore:EPackage>
