<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UseCasesProv" nsURI="http://fr.inria.diverse.puzzle.uml/UseCasesProv" nsPrefix="UseCasesProv">
  <eClassifiers xsi:type="ecore:EClass" name="Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoint" upperBound="-1" eType="//ExtensionPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" upperBound="-1" eType="//Extend" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1" eType="//Include"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCase" lowerBound="1" eType="//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extend">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionLocation" lowerBound="1" upperBound="-1" eType="//ExtensionPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1" eType="//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedCase" lowerBound="1" eType="//UseCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includingCase" lowerBound="1" eType="//UseCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addition" lowerBound="1" eType="//UseCase"/>
  </eClassifiers>
</ecore:EPackage>
