<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InteractionsProv" nsURI="http://fr.inria.diverse.puzzle.uml/InteractionsProv" nsPrefix="InteractionsProv">
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="covered" upperBound="-1" eType="//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalOrdering" upperBound="-1" eType="//GeneralOrdering" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingOperand" eType="//InteractionOperand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionSpecification" abstract="true" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="//OccurenceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" lowerBound="1" eType="//OccurenceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccurenceSpecification" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBefore" upperBound="-1" eType="//GeneralOrdering"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toAfter" upperBound="-1" eType="//GeneralOrdering"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateInvariant" eSuperTypes="//InteractionFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" upperBound="-1" eType="//InteractionFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" upperBound="-1" eType="//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalGate" upperBound="-1" eType="//Gate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredBy" upperBound="-1" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" lowerBound="1" eType="//Interaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposedAs" eType="//PartDecomposition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendEvent" eType="//MessageEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEvent" eType="//MessageEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEnd" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionOccurrenceSpecification" eSuperTypes="//OccurenceSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="execution" lowerBound="1" eType="//ExecutionSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageOccurrenceSpecification" eSuperTypes="//OccurenceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestructionOccurrenceSpecification" eSuperTypes="//MessageOccurrenceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorExecutionSpecification" eSuperTypes="//ExecutionSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionExecutionSpecification" eSuperTypes="//ExecutionSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralOrdering">
    <eStructuralFeatures xsi:type="ecore:EReference" name="after" lowerBound="1" eType="//OccurenceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="before" lowerBound="1" eType="//OccurenceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" upperBound="-1" eType="//InteractionFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="//InteractionConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" eType="//InteractionOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cfragmentGate" upperBound="-1" eType="//Gate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsiderIgnoreFragment" eSuperTypes="//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Continuation" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setting">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" eSuperTypes="//MessageEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionUse" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualGate" upperBound="-1" eType="//Gate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refersTo" lowerBound="1" eType="//Interaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartDecomposition" eSuperTypes="//InteractionUse"/>
</ecore:EPackage>
