<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InteractionsReq" nsURI="http://fr.inria.diverse.puzzle.uml/InteractionsReq" nsPrefix="InteractionsReq">
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
