<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NotTriggerModuleProv" nsURI="NotTriggerModuleProv" nsPrefix="NotTriggerModuleProv">
  <eClassifiers xsi:type="ecore:EClass" name="NotTrigger" eSuperTypes="//Trigger">
    <eOperations name="evalTrigger">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="events">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1" eType="//Trigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrTrigger" eSuperTypes="//Trigger">
    <eOperations name="evalTrigger">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="events">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="//Trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="//Trigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger"/>
</ecore:EPackage>
