/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.serializer;

import fr.inria.diverse.puzzle.serializer.AbstractMutivarSyntacticSequencer;

@SuppressWarnings("all")
public class MutivarSyntacticSequencer extends AbstractMutivarSyntacticSequencer {
}
