/**
 * generated by Xtext
 */
package fr.inria.diverse.puzzle.serializer;

import fr.inria.diverse.puzzle.serializer.AbstractMutivarSemanticSequencer;

@SuppressWarnings("all")
public class MutivarSemanticSequencer extends AbstractMutivarSemanticSequencer {
}
