package fr.inria.diverse.puzzle.validator.vos;

public enum PuzzleDiagnosisItemKind {
	INVALID_ABSTRACT_IMPLEMENTATION,
	INVALID_INTERFACE_IMPLEMENTATION,
	INCOHERENT_CONTAINMENT_REFERENCES,
	INCOHERENT_ORDERED_FEATURES,
	INCOHERENT_UNIQUE_FEATURES,
	INCOHERENT_ATTRIBUTE_DATATYPES,
	MULTIPLICITY_MISMATCH
}
