<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsm" nsURI="http://puzzle.examples.fsm" nsPrefix="fsm">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1"
        eType="#//AbstractState" containment="true" eOpposite="#//AbstractState/region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//State"
        eOpposite="#//State/ownedRegions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region" eOpposite="#//Region/subvertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//AbstractState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doActivity" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRegions" upperBound="-1"
        eType="#//Region" containment="true" eOpposite="#//Region/stateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Trigger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractState" eOpposite="#//AbstractState/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractState" eOpposite="#//AbstractState/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" upperBound="-1"
        eType="#//Statement" containment="true">
      <eAnnotations source="addition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//Trigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Trigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Trigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" abstract="true" eSuperTypes="#//AbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeepHistory" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShallowHistory" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Junction" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//Context"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecl" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignation" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
