<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ActivitiesProv" nsURI="http://fr.inria.diverse.puzzle.uml/ActivitiesProv" nsPrefix="ActivitiesProv">
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSingleExecution">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" upperBound="-1" eType="//ActivityGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="//ActivityEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partition" upperBound="-1" eType="//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredNode" upperBound="-1" eType="//StructuredActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inGroup" upperBound="-1" eType="//ActivityGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedNode" upperBound="-1" eType="//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPartition" upperBound="-1" eType="//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inInterruptibleRegion" eType="//InterruptibleActivityRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStructuredNode" eType="//StructuredActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subgroup" upperBound="-1" eType="//ActivityGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superGroup" eType="//ActivityGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inActivity" eType="//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedNode" upperBound="-1" eType="//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedEdge" upperBound="-1" eType="//ActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNode" abstract="true" eSuperTypes="//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityParameterNode" eSuperTypes="//ObjectNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode" abstract="true" eSuperTypes="//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode" eSuperTypes="//ControlNode //FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedEdge" upperBound="-1" eType="//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inGroup" upperBound="-1" eType="//ActivityGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPartition" upperBound="-1" eType="//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interrupts" eType="//InterruptibleActivityRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStructuredNode" eType="//StructuredActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" eSuperTypes="//ActivityEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlow" eSuperTypes="//ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMulticast">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultireceive">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControlType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CentralBufferNode" eSuperTypes="//ObjectNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" abstract="true" eSuperTypes="//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowFinalNode" eSuperTypes="//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode" eSuperTypes="//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCombineDuplicate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode" eSuperTypes="//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisionInputFlow" eType="//ObjectFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPartition" eSuperTypes="//ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpartition" upperBound="-1" eType="//ActivityPartition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superPartition" eType="//ActivityPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStoreNode" eSuperTypes="//CentralBufferNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptibleActivityRegion" eSuperTypes="//ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interruptingEdge" upperBound="-1" eType="//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredActivityNode" eSuperTypes="//ExecutableNode //ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mustIsolate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="//ActivityEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableNode" eSuperTypes="//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handler" upperBound="-1" eType="//ExceptionHandler" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopNode" eSuperTypes="//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTestedFirst">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setupPart" upperBound="-1" eType="//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyPart" upperBound="-1" eType="//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" upperBound="-1" eType="//ExecutableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalNode" eSuperTypes="//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDeterminate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAssumed">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clause" lowerBound="1" upperBound="-1" eType="//Clause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" upperBound="-1" eType="//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" upperBound="-1" eType="//ExecutableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessorClause" upperBound="-1" eType="//Clause"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sucessorClause" upperBound="-1" eType="//Clause"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceNode" eSuperTypes="//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableNode" upperBound="-1" eType="//ExecutableNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlerBody" lowerBound="1" eType="//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectedNode" lowerBound="1" eType="//ExecutableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionInput" lowerBound="1" eType="//ObjectNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpansionRegion" eSuperTypes="//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputElement" lowerBound="1" upperBound="-1" eType="//ExpansionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputElement" upperBound="-1" eType="//ExpansionNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpansionNode" eSuperTypes="//ObjectNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionAsInput" eType="//ExpansionRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regionAsOutput" eType="//ExpansionRegion"/>
  </eClassifiers>
</ecore:EPackage>
