<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ActivitiesReq" nsURI="http://fr.inria.diverse.puzzle.uml/ActivitiesReq" nsPrefix="ActivitiesReq">
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true" eSuperTypes="//Class">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinableElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioralFeature" abstract="true" eSuperTypes="//Namespace //Feature">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="//MultiplicityElement //TypedElement">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElement" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin">
    <eAnnotations source="Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true">
    <eAnnotations source="Required"/>
  </eClassifiers>
</ecore:EPackage>
