/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MutivarRuntimeModule extends fr.inria.diverse.puzzle.AbstractMutivarRuntimeModule {

}
