/*
 * generated by Xtext
 */
package fr.inria.diverse.puzzle;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MutivarStandaloneSetup extends MutivarStandaloneSetupGenerated{

	public static void doSetup() {
		new MutivarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

